
"""
Name matching utilities for district resolution.
"""
from typing import Optional

# Normalized corrections map
NAME_CORRECTIONS = {
    # Spelling variants
    "anantapuramu": "anantapur", "srikakulum": "srikakulam",
    "visakhapatnam": "visakhapatanam", "kokrajihar": "kokrajhar",
    "nalbali": "nalbari", "sibsagar": "sivasagar",
    "purnea": "purnia", "monghyr": "munger",
    "chittaurgarh": "chittorgarh", "darjiling": "darjeeling",
    "giridh": "giridih", "hazaribag": "hazaribagh",
    "sahibganj": "sahebganj", "baramula": "baramulla",
    "dakshina kannad": "dakshina kannada",
    "jayashankar bhupalpally": "jayashankar bhupalapally",
    "tiruchchirappalli": "tiruchirappalli",
    "tiruchirapalli": "tiruchirappalli",
    "kancheepuram": "kanchipuram",
    "dakshin bastar dantewada": "dantewada",
    "raj nandgaon": "rajnandgaon",
    "purba champaran": "purbi champaran",
    "pashchim champaran": "west champaran",
    # Renamed districts
    "gurgaon": "gurugram", "bangalore": "bengaluru urban",
    "bangalore rural": "bengaluru rural", "bijapur": "vijayapura",
    "gulbarga": "kalaburagi", "mysore": "mysuru",
    "belgaum": "belagavi", "bellary": "ballari",
    "hoshangabad": "narmadapuram", "allahabad": "prayagraj",
    "faizabad": "ayodhya", "cannanore": "kannur",
    "quilon": "kollam", "trichur": "thrissur",
    "palghat": "palakkad",
    # Historical/composite names (map to first split child if existing)
    "champaran": "purbi champaran", "shahabad": "rohtas",
    "greater bombay": "mumbai", "west nimar": "khargone",
    "nimar": "khargone", "simla": "shimla",
    "lahaul and spiti": "lahul and spiti",
    "alleppey": "alappuzha",
    # Advanced mapped aliases
    "nicobar": "nicobars",
    "north & middle andaman": "north and middle andaman",
    "south andaman": "south andamans",
    "lepa - rada": "leparada",
    "pakke-kesang": "pakke kessang",
    "shi-yomi": "shi yomi",
    "subansiri": "upper subansiri",
    "dhuburi": "dhubri",
    "kamrup metropolitan": "kamrup metro",
    "south salmara-mankachar": "south salmara mancachar",
    "gaurela-pendra-marwahi": "gaurella pendra marwahi",
    "ahmedabad": "ahmadabad",
    "aravalli": "arvalli",
    "chhota udepur": "chhotaudepur",
    "mehsana": "mahesana",
    "charkhi dadri": "charki dadri",
    "kulu": "kullu",
    "badgam": "budgam",
    "bandipore": "bandipora",
    "rajauri": "rajouri",
    "shupiyan": "shopian",
    "kodarma": "koderma",
    "pakaur": "pakur",
    "saraikela-kharsawan": "saraikela kharsawan",
    "singhbhum": "west singhbhum",
    "bagalkot": "bagalkote",
    "chamarajanagar": "chamarajanagara",
    "davanagere": "davangere",
    "vijayanagara": "vijayanagar",
    "kasargod": "kasaragod",
    "agar-malwa": "agar malwa",
    "annupur": "anuppur",
    "narsimhapur": "narsinghpur",
    "gondiya": "gondia",
    "mumbai": "mumbai suburban",
    "garo hills": "west garo hills",
    "jaintia hills": "west jaintia hills",
    "hnathial": "hnahthial",
    "tseminyü": "tseminyu",
    "baudh": "boudh",
    "debagarh": "deogarh",
    "nabarangapur": "nabarangpur",
    "sonapur": "sonepur",
    "bhatinda": "bathinda",
    "firozpur": "ferozepur",
    "sahibzada ajit singh nagar": "shahid bhagat singh nagar",
    "dhaulpur": "dholpur",
    "chengalpattu mgr": "chengalpattu",
    "dindigul anna": "dindigul",
    "tirupattur": "tirupathur",
    "viluppuram": "villupuram",
    "jagtial": "jagitial",
    "jangaon": "jangoan",
    "mahbubnagar": "mahabubnagar",
    "medchal–malkajgiri": "medchal malkajgiri",
    "rangareddi": "ranga reddy",
    "rangareddy": "ranga reddy",
    "sipahijala": "sepahijala",
    "etawah'": "etawah",
    "kanpur": "jaunpur",
    "kanshiram nagar": "kushi nagar",
    "kushinagar": "kushi nagar",
    "sant kabir nagar": "sant kabeer nagar",
    "shrawasti": "shravasti",
    "siddharthnagar": "siddharth nagar",
    "rudraprayag": "rudra prayag",
    "udham singh nagar": "udam singh nagar",
    "medinipur": "medinipur west",
    "pashchim barddhaman": "paschim bardhaman",
    "purba barddhaman": "purba bardhaman",
    "dr. b. r. ambedkar konaseema": "konaseema",
    "nellore": "spsr nellore",
    "sri potti sriramulu nellore": "spsr nellore",
    "balipara frontier tract": "west kameng",
    "mikir hills": "karbi anglong",
    "north cachar hills": "dima hasao",
    "punch": "poonch",
    "pashchimi singhbhum": "west singhbhum",
    "purbi singhbhum": "east singhbhum",
    "phulabani": "kandhamal",
    "muktsar": "sri muktsar sahib",
    "nawanshahr": "shahid bhagat singh nagar",
    "ropar": "rupnagar",
    "kamarajar": "virudhunagar",
    "north arcot": "vellore",
    "periyar": "erode",
    "south arcot": "cuddalore",
    "tirunelveli kattabomman": "tirunelveli",
    "kumuram bheem": "komaram bheem asifabad",
    "warangal rural": "warangal",
    "jyotiba phule nagar": "amroha",
    "sant ravidas nagar": "bhadohi",
    "garhwal": "pauri garhwal",
    "barddhaman": "purba bardhaman",
    "twenty four parganas": "north twenty four parganas",
    "warangal urban (hanamkonda)": "hanamkonda",
    "hapur (panchsheel nagar)": "hapur",
    "sambhal (bhimnagar)": "sambhal",
    "shamli (prabuddhanagar)": "shamli",
}

STATE_ALIASES = {
    "andhra pradesh-telangana": ["TELANGANA", "ANDHRA PRADESH"],
    "daman and diu": ["THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU"],
}

TELANGANA_DISTRICTS = {
    "adilabad", "karimnagar", "warangal", "khammam", "nalgonda",
    "medak", "nizamabad", "rangareddy", "rangareddi", "mahabubnagar",
    "hyderabad",
}

def resolve_district_name(district_name: str, state_name: Optional[str] = None) -> str:
    """
    Resolve a district name to its canonical form used in the database.
    """
    dn = district_name.lower().strip()
    
    # Check map
    if dn in NAME_CORRECTIONS:
        return NAME_CORRECTIONS[dn]
        
    return dn
